version: "3.3"

services:
  be-project-monitoring:
    environment:
      APP_DSN: postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable&connect_timeout=5
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    networks:
      - backend
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    restart: always
    ports:
      - "5432:5432"
    networks:
      - backend

networks:
  backend:
    driver: bridge